/**
 * Produces the icon-level QA record.
 *
 *   qa/icon-qa-report.md    per-icon geometry, provenance and review state
 *   qa/contact-sheet.html   every released icon at 16/20/24/32/48 px, both themes
 *   qa/before-after.html    v3 originals beside the drawings that superseded them
 *   qa/bounds.json          machine-readable geometry, for regression diffing
 *
 * The bounds file is the visual-regression baseline: geometry is deterministic,
 * so a drawing that shifts shows up as a diff without needing image snapshots.
 */

import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { PATHS, ROOT, listSvgAssets, loadCategories, loadIcons, relative } from './lib/repo.ts';
import { iconBody } from './lib/generators.ts';
import { measureAsset, validateAsset } from './lib/validate.ts';
import { parseSvg } from './lib/svg-document.ts';

const QA_DIR = path.join(ROOT, 'qa');
const SIZES = [16, 20, 24, 32, 48] as const;

function escapeHtml(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function svgTag(body: string, size: number): string {
  return (
    `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" ` +
    `stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${body}</svg>`
  );
}

const PAGE_CSS = `
:root { color-scheme: light dark; --paper:#FAF9F6; --ink:#16150F; --line:#E2DED3; --muted:#56524A; }
@media (prefers-color-scheme: dark){ :root{ --paper:#12110D; --ink:#F2F0E9; --line:#2C2A23; --muted:#B0AA9C; } }
body{margin:0;padding:32px;background:var(--paper);color:var(--ink);font:14px/1.5 ui-sans-serif,system-ui,sans-serif}
h1{font-size:20px;margin:0 0 4px}p.lede{margin:0 0 24px;color:var(--muted)}
table{border-collapse:collapse;width:100%;max-width:860px}
th,td{border-bottom:1px solid var(--line);padding:10px 8px}
th{text-align:left;font-weight:400;font:12px ui-monospace,SFMono-Regular,Menlo,monospace}
th span{display:block;font-size:11px;color:var(--muted);margin-top:2px}
td{text-align:center;width:76px;vertical-align:middle}
thead td{font-size:11px;color:var(--muted)}
.dark-strip{margin-top:40px;padding:24px;border-radius:8px;background:var(--ink);color:var(--paper);
  display:flex;flex-wrap:wrap;gap:20px;align-items:center}
`;

async function main(): Promise<number> {
  const [icons, categories, assets] = await Promise.all([
    loadIcons(),
    loadCategories(),
    listSvgAssets(PATHS.iconsSvgRoot),
  ]);

  const bodies = new Map(assets.map((asset) => [asset.id, iconBody(asset.source)]));
  const sources = new Map(assets.map((asset) => [asset.id, asset.source]));
  const categoryLabels = new Map(categories.map((category) => [category.id, category.label]));

  await mkdir(QA_DIR, { recursive: true });

  /* ---------------- bounds baseline + report ---------------- */

  const rows = icons.map((icon) => {
    const source = sources.get(icon.id) ?? '';
    const { geometry, stroked } = measureAsset(parseSvg(source));
    const findings = validateAsset({ file: `${icon.id}.svg`, source });
    return { icon, geometry, stroked, findings };
  });

  await writeFile(
    path.join(QA_DIR, 'bounds.json'),
    `${JSON.stringify(
      Object.fromEntries(rows.map((row) => [row.icon.id, row.geometry])),
      null,
      2,
    )}\n`,
    'utf8',
  );

  const failing = rows.filter((row) => row.findings.length > 0);

  const report = [
    '# Icon QA report',
    '',
    `Generated by \`npm run qa\` from the repository. ${icons.length} released icons, ` +
      `${new Set(icons.map((icon) => icon.category)).size} categories in use.`,
    '',
    '## Result',
    '',
    failing.length === 0
      ? 'Every released icon passes every automated rule: canvas containment including the stroke ' +
        'halo, the 2-unit live area, prohibited text, hard-coded colour, the element and attribute ' +
        'allow-lists, and metadata agreement.'
      : `${failing.length} icon(s) fail an automated rule. This is a release blocker.`,
    '',
    '## Geometry',
    '',
    'Bounds are the true geometric extents — cubics solved for extrema, arcs converted to cubics ' +
      'first — not sampled endpoints. The canvas is 24 units; the live area is `[2, 22]` on both axes.',
    '',
    '| Icon | Category | x | y | Live area | Source |',
    '| --- | --- | --- | --- | --- | --- |',
    ...rows.map((row) => {
      const { geometry, icon } = row;
      const inLive =
        geometry.minX >= 2 && geometry.minY >= 2 && geometry.maxX <= 22 && geometry.maxY <= 22;
      return (
        `| \`${icon.id}\` | ${categoryLabels.get(icon.category) ?? icon.category} ` +
        `| ${geometry.minX} – ${geometry.maxX} | ${geometry.minY} – ${geometry.maxY} ` +
        `| ${inLive ? 'pass' : 'FAIL'} | \`${icon.provenance.source}\` |`
      );
    }),
    '',
    '## Provenance mix',
    '',
    '| Source | Count | What it means |',
    '| --- | --- | --- |',
    `| \`v3-audit-drawing\` | ${icons.filter((i) => i.provenance.source === 'v3-audit-drawing').length} | Descends from one of the audit's eighteen vector drawings |`,
    `| \`v2-asset-redrawn\` | ${icons.filter((i) => i.provenance.source === 'v2-asset-redrawn').length} | The audit judged a raster asset but produced no vector; drawn fresh to spec |`,
    `| \`v3-audit-roadmap\` | ${icons.filter((i) => i.provenance.source === 'v3-audit-roadmap').length} | A gap the audit named and never drew |`,
    '',
    '## Cultural review state',
    '',
    '| Icon | Review | Local names |',
    '| --- | --- | --- |',
    ...icons.map(
      (icon) =>
        `| \`${icon.id}\` | ${icon.culturalReview.status} | ` +
        `${icon.localNames.length === 0 ? '—' : icon.localNames.map((n) => `${n.value} (${n.language}, ${n.review})`).join(', ')} |`,
    ),
    '',
    '## Weights',
    '',
    `Drawn: \`${[...new Set(icons.flatMap((icon) => icon.weights))].join('`, `')}\`. ` +
      'Specified and undrawn: `thin`, `bold`, `fill`. No weight in this library is produced by ' +
      'changing `stroke-width` on another weight.',
    '',
    '## Visual review',
    '',
    'Automated rules cannot judge legibility. Open `qa/contact-sheet.html` and check every icon at ' +
      '16 px: if a glyph becomes a smudge, it is not an icon regardless of its geometry. ' +
      '`qa/before-after.html` shows the v3 originals beside the drawings that superseded them.',
    '',
  ].join('\n');

  await writeFile(path.join(QA_DIR, 'icon-qa-report.md'), `${report}\n`, 'utf8');

  /* ---------------- contact sheet ---------------- */

  const sheetRows = icons
    .map((icon) => {
      const body = bodies.get(icon.id) ?? '';
      const cells = SIZES.map((size) => `<td>${svgTag(body, size)}</td>`).join('');
      return (
        `<tr><th><code>${escapeHtml(icon.id)}</code>` +
        `<span>${escapeHtml(categoryLabels.get(icon.category) ?? icon.category)}</span></th>${cells}</tr>`
      );
    })
    .join('\n      ');

  const darkStrip = icons.map((icon) => svgTag(bodies.get(icon.id) ?? '', 28)).join('\n        ');

  await writeFile(
    path.join(QA_DIR, 'contact-sheet.html'),
    `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>African Icon Library — contact sheet</title><style>${PAGE_CSS}</style></head>
<body>
  <h1>African Icon Library — contact sheet</h1>
  <p class="lede">${icons.length} released icons, regular weight, at ${SIZES.join(' / ')} px. The 16 px column is the decisive one.</p>
  <table>
    <thead><tr><td></td>${SIZES.map((size) => `<td>${size} px</td>`).join('')}</tr></thead>
    <tbody>
      ${sheetRows}
    </tbody>
  </table>
  <div class="dark-strip">
    ${darkStrip}
  </div>
</body></html>
`,
    'utf8',
  );

  /* ---------------- before / after ---------------- */

  const supersededDir = path.join(ROOT, 'packages/icons/superseded/regular');
  let superseded: string[] = [];
  try {
    superseded = (await readdir(supersededDir)).filter((file) => file.endsWith('.svg'));
  } catch {
    /* nothing superseded yet */
  }

  const comparisons = await Promise.all(
    superseded.map(async (file) => {
      const id = path.basename(file, '.svg');
      const before = iconBody(await readFile(path.join(supersededDir, file), 'utf8'));
      const after = bodies.get(id) ?? '';
      return { id, before, after };
    }),
  );

  await writeFile(
    path.join(QA_DIR, 'before-after.html'),
    `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>African Icon Library — before and after</title>
<style>${PAGE_CSS}</style></head>
<body>
  <h1>Before and after</h1>
  <p class="lede">${comparisons.length === 0 ? 'Nothing has been superseded yet.' : 'v3 originals beside the drawings that replaced them, at 48 and 24 px.'}</p>
  <table>
    <thead><tr><td></td><td>before 48</td><td>after 48</td><td>before 24</td><td>after 24</td></tr></thead>
    <tbody>
      ${comparisons
        .map(
          (comparison) =>
            `<tr><th><code>${escapeHtml(comparison.id)}</code></th>` +
            `<td>${svgTag(comparison.before, 48)}</td><td>${svgTag(comparison.after, 48)}</td>` +
            `<td>${svgTag(comparison.before, 24)}</td><td>${svgTag(comparison.after, 24)}</td></tr>`,
        )
        .join('\n      ')}
    </tbody>
  </table>
</body></html>
`,
    'utf8',
  );

  process.stdout.write(
    [
      `QA report for ${icons.length} icons — ${failing.length === 0 ? 'all rules pass' : `${failing.length} FAILING`}`,
      `  ${relative(path.join(QA_DIR, 'icon-qa-report.md'))}`,
      `  ${relative(path.join(QA_DIR, 'contact-sheet.html'))}`,
      `  ${relative(path.join(QA_DIR, 'before-after.html'))}`,
      `  ${relative(path.join(QA_DIR, 'bounds.json'))}`,
      '',
    ].join('\n'),
  );

  return failing.length === 0 ? 0 : 1;
}

process.exitCode = await main();
